"""
Django settings for prompt_firewall project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import warnings

# --- Load .env file (keeps secrets out of source code) ---
_env_path = Path(__file__).resolve().parent.parent / '.env'
if _env_path.exists():
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _key, _, _val = _line.partition('=')
                _key = _key.strip()
                _val = _val.strip().strip('"').strip("'")
                if _val:
                    os.environ[_key] = _val
    print(f"[promptguard] Loaded .env from {_env_path}")
else:
    print(f"[promptguard] No .env file found at {_env_path}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-me'
)

# Warn loudly if the insecure fallback key is used in production
_INSECURE_KEY = 'django-insecure-dev-only-change-me'
if SECRET_KEY == _INSECURE_KEY and not os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true':
    warnings.warn(
        "\n\n⚠️  SECURITY WARNING: Using the default insecure SECRET_KEY in "
        "production!\nSet DJANGO_SECRET_KEY in your environment or .env file.\n"
        "Generate one with: python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\"\n",
        stacklevel=1,
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'prompt_firewall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'web' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prompt_firewall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'web' / 'static']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# PromptGuard — Gemini API key for generative analysis
# Reads from .env file or environment variable (never hardcode keys here)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', os.environ.get('GOOGLE_API_KEY', ''))

# --- Rate Limiting ---
# Uses Django's built-in cache. Switch to Redis for production.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'promptguard-ratelimit',
    }
}
RATE_LIMIT_PER_MINUTE = int(os.environ.get('RATE_LIMIT_PER_MINUTE', '30'))

# --- Webhook Alerting ---
# Set PROMPTGUARD_WEBHOOK_URL to receive real-time alerts on BLOCK events.
# e.g. Slack incoming webhook, PagerDuty, or a custom endpoint.
PROMPTGUARD_WEBHOOK_URL = os.environ.get('PROMPTGUARD_WEBHOOK_URL', '')
PROMPTGUARD_WEBHOOK_THRESHOLD = int(os.environ.get('PROMPTGUARD_WEBHOOK_THRESHOLD', '80'))

# --- Downstream LLM API Keys (server-side only) ---
# Keys are resolved exclusively from environment variables.
# Clients should NEVER send API keys in request bodies.
LLM_API_KEYS = {
    'openai':    os.environ.get('OPENAI_API_KEY', ''),
    'gpt':       os.environ.get('OPENAI_API_KEY', ''),
    'claude':    os.environ.get('ANTHROPIC_API_KEY', ''),
    'anthropic': os.environ.get('ANTHROPIC_API_KEY', ''),
    'gemini':    os.environ.get('GEMINI_API_KEY', os.environ.get('GOOGLE_API_KEY', '')),
    'google':    os.environ.get('GEMINI_API_KEY', os.environ.get('GOOGLE_API_KEY', '')),
    'ollama':    '',  # Ollama is local, no key needed
}

# --- Output Response Scanning ---
# When enabled, LLM responses are scanned before being returned to the user.
OUTPUT_SCANNING_ENABLED = os.environ.get('OUTPUT_SCANNING_ENABLED', 'True').lower() == 'true'
