# Generated by Django 6.0.5 on 2026-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('decision', models.CharField(max_length=10)),
                ('threat_level', models.CharField(max_length=10)),
                ('risk_score', models.IntegerField()),
                ('attack_types', models.JSONField(default=list)),
                ('reasons', models.JSONField(default=list)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('llm_used', models.CharField(blank=True, max_length=50, null=True)),
                ('llm_response', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
