# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='event_type',
            field=models.CharField(choices=[('ANALYZE', 'Analyze only'), ('FIREWALL', 'Firewall decision'), ('LLM_FORWARD', 'Forwarded to LLM'), ('LLM_ERROR', 'LLM adapter error')], default='ANALYZE', max_length=20),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='forwarded_to_llm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='llm_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='path',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='proceeded_after_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='prompt_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='prompt_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='semantic_attack_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['event_type', '-created_at'], name='api_promptl_event_t_270ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['decision', '-created_at'], name='api_promptl_decisio_7a4485_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['forwarded_to_llm', '-created_at'], name='api_promptl_forward_1331dc_idx'),
        ),
    ]
