# Generated by Django 6.0.5 on 2026-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promptlog_audit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promptlog',
            new_name='api_promptl_event_t_8b269d_idx',
            old_name='api_promptl_event_t_270ae6_idx',
        ),
        migrations.RenameIndex(
            model_name='promptlog',
            new_name='api_promptl_decisio_0c92ba_idx',
            old_name='api_promptl_decisio_7a4485_idx',
        ),
        migrations.RenameIndex(
            model_name='promptlog',
            new_name='api_promptl_forward_97ffc3_idx',
            old_name='api_promptl_forward_1331dc_idx',
        ),
        migrations.RemoveField(
            model_name='promptlog',
            name='semantic_attack_type',
        ),
        migrations.RemoveField(
            model_name='promptlog',
            name='semantic_score',
        ),
        migrations.AddField(
            model_name='promptlog',
            name='ai_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
